import Head from 'next/head';
import { createClient } from 'contentful';

import Layout from '../../components/blog/layout/layout';
import MainContent from '../../components/blog/mainContent/mainContent';
import Context from '../../store';

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY,
  });

  const res = await client.getEntries({ content_type: 'blog' });

  return {
    props: {
      blogs: res.items,
    },
    revalidate: 1,
  };
}

export default function Blog({ blogs }) {
  return (
    <Context>
      <Layout>
        <Head>
          <title>Rahsand- Blog</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MainContent blogs={blogs} />
      </Layout>
    </Context>
  );
}
