import Head from 'next/head';
import Layout from '../components/blog/layout/layout';
import MainContent from '../components/blog/mainContent/mainContent';
import SearchContextProvider from '../store/search-context';

export default function Blog() {
  return (
    <SearchContextProvider>
      <Layout>
        <Head>
          <title>Rahsand- Blog</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MainContent />
      </Layout>
    </SearchContextProvider>
  );
}
