import Head from 'next/head';
import Layout from '../components/blog/layout/layout';
import MainContent from '../components/blog/mainContent/mainContent';
import Context from '../store';

export default function Blog() {
  return (
    <Context>
      <Layout>
        <Head>
          <title>Rahsand- Blog</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <MainContent />
      </Layout>
    </Context>
  );
}
