import Head from 'next/head';

import Layout from '../components/portfolio/layout/layout';
import HeroSection from '../components/portfolio/home/heroSection';
import ProjectSection from '../components/portfolio/home/projectSection';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeroSection />
      <ProjectSection />
    </Layout>
  );
}
