import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

import Layout from '../components/portfolio/layout/layout';
import HeroSection from '../components/portfolio/home/heroSection';
import ProjectSection from '../components/portfolio/home/projectSection';
import { Button } from '../styles/blog/globalStyles';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    setTimeout(() => {
      router.replace('/blog');
    }, 4000);
  }, []);
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div
        style={{
          position: 'fixed',
          top: '50%',
          left: '50%',
          transform: 'translate(-50%, -50%)',
        }}
      >
        <h1>Work under process!</h1>
        <p>You'll be redirected in 4 seconds...</p>
        <Link href={'/blog'}>
          <a>
            <Button>Blog</Button>
          </a>
        </Link>
      </div>
      {/* <HeroSection />
      <ProjectSection /> */}
    </Layout>
  );
}
